//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAppServer")]
    public interface IAppServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServer/GetStringFromWCF", ReplyAction="http://tempuri.org/IAppServer/GetStringFromWCFResponse")]
        string GetStringFromWCF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServer/GetStringFromWCF", ReplyAction="http://tempuri.org/IAppServer/GetStringFromWCFResponse")]
        System.Threading.Tasks.Task<string> GetStringFromWCFAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppServerChannel : ConApp.ServiceReference1.IAppServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppServerClient : System.ServiceModel.ClientBase<ConApp.ServiceReference1.IAppServer>, ConApp.ServiceReference1.IAppServer {
        
        public AppServerClient() {
        }
        
        public AppServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStringFromWCF() {
            return base.Channel.GetStringFromWCF();
        }
        
        public System.Threading.Tasks.Task<string> GetStringFromWCFAsync() {
            return base.Channel.GetStringFromWCFAsync();
        }
    }
}
