#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFHost
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test")]
	public partial class InstanceStoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public InstanceStoreDataContext() : 
				base(global::WFHost.Properties.Settings.Default.testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InstanceStoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InstanceStoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InstanceStoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InstanceStoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DocumentReviewTask> DocumentReviewTasks
		{
			get
			{
				return this.GetTable<DocumentReviewTask>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocumentReviewTask")]
	public partial class DocumentReviewTask
	{
		
		private long _SurrogateInstanceId;
		
		private string _PromotionName;
		
		private object _TicketId;
		
		public DocumentReviewTask()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurrogateInstanceId", DbType="BigInt NOT NULL")]
		public long SurrogateInstanceId
		{
			get
			{
				return this._SurrogateInstanceId;
			}
			set
			{
				if ((this._SurrogateInstanceId != value))
				{
					this._SurrogateInstanceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromotionName", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string PromotionName
		{
			get
			{
				return this._PromotionName;
			}
			set
			{
				if ((this._PromotionName != value))
				{
					this._PromotionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketId", DbType="Variant", UpdateCheck=UpdateCheck.Never)]
		public object TicketId
		{
			get
			{
				return this._TicketId;
			}
			set
			{
				if ((this._TicketId != value))
				{
					this._TicketId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
